# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSquad < Formula
  desc "Manage multiple AI agents like Claude Code, Aider, and more. 10x your productivity."
  homepage "https://smtg-ai.github.io/claude-squad/"
  version "1.0.4"
  license "AGPL-3.0"

  depends_on "gh" => :optional
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_amd64.tar.gz"
      sha256 "d26dbd603a94021284cec1d80683a60b927f7786bff7df2f5ad7e4ccb3dbd17a"

      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_arm64.tar.gz"
      sha256 "e1fa776d5a927ee313457b78aeb05734078b9f8c97d7ec016eb2292ea5129125"

      def install
        bin.install "claude-squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_amd64.tar.gz"
      sha256 "473d729e9a59ac995fed6bdd81f7ef7d80f3675017ed9611857a9ddc934058f2"
      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_arm64.tar.gz"
      sha256 "2b46ebef2a33b05b0b1ade1ca9bd21e1064f6e5b393c3373c1684658c8e3dc11"
      def install
        bin.install "claude-squad"
      end
    end
  end

  test do
    system "#{bin}/cs version"
  end
end
