# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSquad < Formula
  desc "Manage multiple AI agents like Claude Code, Aider, and more. 10x your productivity."
  homepage "https://smtg-ai.github.io/claude-squad/"
  version "1.0.4"
  license "AGPL-3.0"

  depends_on "gh" => :optional
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_amd64.tar.gz"
      sha256 "73c3b0c763cd0b4566136589f3f764224d02d112fdaf8bcfd7a99af637a800a6"

      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_arm64.tar.gz"
      sha256 "a7f977a2b89938f2e6be81fca1e455c9d44e7185e9c66617df2965514cf6a286"

      def install
        bin.install "claude-squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_amd64.tar.gz"
      sha256 "b9a78f15ebf65a765c388e7a4c7c4b749af7133b38ab505f33cd953f6d4b7fa1"
      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_arm64.tar.gz"
      sha256 "2d7f553251ef408dddecdf815f053c0b2ec7c041163decbdfbeae1adaec19a4d"
      def install
        bin.install "claude-squad"
      end
    end
  end

  test do
    system "#{bin}/cs version"
    # ...
  end
end
