# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSquad < Formula
  desc "Manage multiple AI agents like Claude Code, Aider, and more. 10x your productivity."
  homepage "https://smtg-ai.github.io/claude-squad/"
  version "1.0.4"
  license "AGPL-3.0"

  depends_on "gh" => :optional
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_amd64.tar.gz"
      sha256 "3fc372411e20a13eb9dd7fb2bce793e5a49849f3e14c20ce905a4064ec0c6fa2"

      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_darwin_arm64.tar.gz"
      sha256 "693b26f8a449c88fcec91dda2eb3cecbbf477e58470f2db38d47b234f9a842a9"

      def install
        bin.install "claude-squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_amd64.tar.gz"
      sha256 "f5475838ce8f9d1cecdd6d4cdd6e82aad596ed796fc435ca181e745376fa07bb"
      def install
        bin.install "claude-squad"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/smtg-ai/claude-squad/releases/download/v1.0.4/claude-squad_1.0.4_linux_arm64.tar.gz"
      sha256 "33ce385e891c36f2c50f7b5a06f84a42dff71425e4db0e66d39a51c6205acc99"
      def install
        bin.install "claude-squad"
      end
    end
  end

  test do
    system "#{bin}/cs version"
    # ...
  end
end
